Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2021-07, with the labels that each got.

#4 Update module and import paths to new `redhat-openshift-ecosystem/openshift-preflight` home
  HACK.md
  Makefile
  certification/engine/engine.go
  certification/formatters/formatters.go
  certification/formatters/generic.go
  certification/formatters/junitxml.go
  certification/formatters/util.go
  certification/internal/shell/base_on_ubi.go
  certification/internal/shell/engine.go
  certification/internal/shell/fake_podman_engine.go
  certification/internal/shell/has_license.go
  certification/internal/shell/has_minimal_vulns.go
  certification/internal/shell/has_prohibited_packages.go
  certification/internal/shell/has_required_labels.go
  certification/internal/shell/has_unique_tag.go
  certification/internal/shell/less_than_max_layers.go
  certification/internal/shell/podman.go
  certification/internal/shell/runs_as_nonroot.go
  certification/internal/shell/util.go
  certification/internal/shell/validate_operator_bundle.go
  certification/runtime/runtime.go
  cmd/parse.go
  cmd/root.go
  go.mod
  go.sum
  main.go
Labels: lgtm

#5 Add version flag support
  Makefile
  README.md
  cmd/root.go
  version/version.go
Labels: lgtm

#8 Add unit tests for config precedence parsing function
  cmd/parse_test.go
  cmd/suite_test.go
Labels: lgtm

#9 adding separate policy maps for Operators and Containers
  certification/engine/engine.go
Labels: lgtm

#13 Remove logger as a parameter
  certification/certification.go
  certification/engine/engine.go
  certification/generic_check.go
  certification/internal/shell/base_on_ubi.go
  certification/internal/shell/base_on_ubi_test.go
  certification/internal/shell/engine.go
  certification/internal/shell/has_license.go
  certification/internal/shell/has_minimal_vulns.go
  certification/internal/shell/has_prohibited_packages.go
  certification/internal/shell/has_required_labels.go
  certification/internal/shell/has_unique_tag.go
  certification/internal/shell/less_than_max_layers.go
  certification/internal/shell/runs_as_nonroot.go
  certification/internal/shell/shell_suite_test.go
  certification/internal/shell/validate_operator_bundle.go
  cmd/log.go
  cmd/root.go
Labels: lgtm

#21 Add OWNERS file for openshift-ci
  OWNERS
Labels: lgtm

#22 Move some redundant code to a helper function
  certification/engine/engine.go
Labels: lgtm

#6 Migrate check to scan the containers for unacceptable vulnerabilities
  .gitignore
  Vagrantfile
  certification/internal/shell/has_minimal_vulns.go
  certification/internal/utils/file/helper.go
Labels: lgtm

#1 Refactor BasedOnUbi check and corresponding unit test
  certification/errors/errors.go
  certification/internal/shell/base_on_ubi.go
  certification/internal/shell/base_on_ubi_test.go
  certification/internal/shell/fake_podman_engine.go
  certification/internal/shell/fake_podman_engine_test.go
  certification/internal/shell/shell.go
  certification/internal/shell/shell_suite_test.go
Labels: lgtm

#47 Remove unneeded hack file
  HACK.md
Labels: lgtm

#2 Expand the PodmanEngine and refactor to use it
  certification/errors/errors.go
  certification/internal/shell/base_on_ubi_test.go
  certification/internal/shell/engine.go
  certification/internal/shell/fake_podman_engine_test.go
  certification/internal/shell/has_required_labels.go
  certification/internal/shell/has_required_labels_test.go
  certification/internal/shell/podman.go
  certification/internal/shell/shell_suite_test.go
  certification/internal/shell/util.go
  cli/podman.go
Labels: lgtm

#48 Turn on github action using existing make targets
  .github/workflows/go.yml
  Makefile
Labels: lgtm

#57 Fix Makefile bug preventing tests from being detected
  Makefile
Labels: lgtm

#18 add scorecard policies
  certification/engine/engine.go
  certification/internal/shell/scorecard_basic_check_spec.go
  certification/internal/shell/scorecard_olm_suite.go
Labels: lgtm

#65 Fixed error message when failed to pull image from registry
  certification/internal/shell/engine.go
Labels: ok-to-test

#66 Remove junitxml and switch to generic json
  certification/formatters/formatters.go
  certification/formatters/junitxml.go
  cmd/constants.go
Labels: lgtm

#63 Add tests for the engine creation based on the user configuration
  certification/engine/engine_test.go
Labels: lgtm

#69 Add formatter unit tests
  certification/formatters/formatters.go
  certification/formatters/formatters_suite_test.go
  certification/formatters/formatters_test.go
  cmd/check_container.go
  cmd/check_operator.go
  cmd/constants.go
Labels: lgtm

#82 Add log level default definition and use it in logging init
  cmd/defaults.go
  cmd/root.go
Labels: lgtm

#83 Update readme for new cli invocation structure
  README.md
Labels: lgtm

#86 Correct the HasRequiredLabelsCheck metadata
  certification/internal/shell/has_required_labels.go
Labels: lgtm

#84 Simplify the json parsing in HasUniqueTags check
  certification/internal/shell/skopeo.go
Labels: lgtm

#75 Add unit tests for HasMinimalVulnerabilityCheck + code refactoring
  certification/errors/errors.go
  certification/internal/shell/has_minimal_vulns.go
  certification/internal/shell/has_minimal_vulns_test.go
  certification/internal/shell/podman.go
  certification/internal/shell/shell_suite_test.go
  cli/podman.go
Labels: lgtm

#81 Refactor Operator-sdk checks to use an operator-sdk engine
  .gitignore
  certification/errors/errors.go
  certification/internal/shell/operatorsdk.go
  certification/internal/shell/scorecard_basic_check_spec.go
  certification/internal/shell/scorecard_basic_check_test.go
  certification/internal/shell/scorecard_check.go
  certification/internal/shell/scorecard_olm_suite.go
  certification/internal/shell/scorecard_olm_suite_test.go
  certification/internal/shell/shell.go
  certification/internal/shell/shell_suite_test.go
  cli/operatorsdk.go
  go.mod
  go.sum
Labels: lgtm

#79 Adding an image build event for pushes to main and for releases
  .github/workflows/build.yml
Labels: lgtm

#89 Fixing a name bug in push-image step
  .github/workflows/build.yml
Labels: kind/bug, lgtm

#91 fix log inconcistency causing config-related log line to have a diferrent format
  cmd/root.go
Labels: lgtm

#90 Add trace and error log lines to osdk Scorecard func
  certification/internal/shell/operatorsdk.go
Labels: lgtm

#70 Add unit tests for HasLicense, HasNoProhibitedPackages, and RunsAsNon…
  certification/internal/shell/has_license.go
  certification/internal/shell/has_license_test.go
  certification/internal/shell/has_prohibited_packages.go
  certification/internal/shell/has_prohibited_packages_test.go
  certification/internal/shell/runs_as_nonroot.go
  certification/internal/shell/runs_as_nonroot_test.go
Labels: lgtm

#85 Write results to disk and to stdout
  certification/formatters/formatters.go
  certification/formatters/formatters_test.go
  cmd/check_container.go
  cmd/check_operator.go
  cmd/utils.go
  cmd/utils_test.go
Labels: lgtm

#92 workaround for operator-sdk returning non-zero even when functional
  certification/internal/shell/operatorsdk.go
Labels: lgtm

#94 Update the ubi version being used
  Dockerfile
Labels: lgtm

#95 Move user-facing results definitions to formatters
  certification/formatters/util.go
  certification/runtime/runtime.go
Labels: lgtm

#102 Add github issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm

#101 Write distinct message for error
  certification/formatters/util.go
  certification/internal/shell/base_on_ubi.go
  certification/internal/shell/has_license.go
  certification/internal/shell/has_minimal_vulns.go
  certification/internal/shell/has_prohibited_packages.go
  certification/internal/shell/has_required_labels.go
  certification/internal/shell/has_unique_tag.go
  certification/internal/shell/less_than_max_layers.go
  certification/internal/shell/runs_as_nonroot.go
  certification/internal/shell/scorecard_basic_check_spec.go
  certification/internal/shell/scorecard_olm_suite.go
  certification/internal/shell/validate_operator_bundle.go
Labels: lgtm

#107 Handle image pull failures gracefully in one place instead of on a per-check basis
  .gitignore
  certification/engine/engine.go
  certification/internal/shell/engine.go
  certification/internal/shell/podman.go
  certification/internal/utils/container/helper.go
  cmd/check_container.go
Labels: lgtm

#103 Fix skopeo list-tags to support image digest
  certification/errors/errors.go
  certification/internal/shell/has_unique_tag.go
  certification/internal/shell/skopeo.go
  certification/internal/shell/skopeo_test.go
Labels: lgtm

#112 update HasRequiredLabels check to fall back to failing
  certification/internal/shell/has_required_labels.go
Labels: lgtm

#117 Expose the checks used by the check container and check operator actions in their help outputs
  cmd/check_container.go
  cmd/check_operator.go
Labels: lgtm

#118 Add overall status of all checks
  certification/formatters/util.go
  certification/internal/shell/engine.go
  certification/runtime/runtime.go
Labels: lgtm

#114 Make operator-sdk scorecard tests pass
  certification/internal/shell/scorecard_check.go
  test/containerfiles/successful-bundle-assets/manifests/operators.my.domain_mykinds.yaml
  test/containerfiles/successful-bundle-assets/manifests/sample-operator.clusterserviceversion.yaml
Labels: lgtm

#120 Add initial installation instructions
  README.md
Labels: lgtm

#105 Improvements to HasLicenseCheck
  certification/internal/shell/has_license.go
  certification/internal/shell/has_license_test.go
  certification/internal/shell/podman.go
  certification/internal/shell/shell_suite_test.go
  cli/podman.go
Labels: lgtm

#122 Catch error in operator policy execution
  cmd/check_operator.go
Labels: lgtm

#123 Add podman create, remove, copyFrom, and skopeo inspect
  certification/internal/shell/podman.go
  certification/internal/shell/shell_suite_test.go
  certification/internal/shell/skopeo.go
  cli/podman.go
  cli/skopeo.go
Labels: lgtm

#127 Fix constant misusing the symbol err
  certification/internal/shell/engine.go
Labels: lgtm

#130 Remove unused CheckEngine and ContainerFileManager and rename CheckRunner to CheckEngine
  certification/engine/engine.go
  certification/internal/shell/engine.go
  docs/dev/README.md
Labels: lgtm

#134 Use boolean value to indicate overall result
  certification/formatters/util.go
  certification/internal/shell/engine.go
  certification/runtime/runtime.go
Labels: lgtm

#135 Add system dependencies required for golang container bindings (PR #50)
  .github/workflows/go.yml
Labels: lgtm

#50 add golang bindings for v2 implementation of preflight
  .github/workflows/go.yml
  certification/errors/errors.go
  certification/internal/bindings/client.go
  certification/internal/bindings/docker.go
  certification/internal/bindings/helpers.go
  certification/internal/bindings/podman.go
  certification/internal/bindings/types.go
  go.mod
  go.sum
Labels: lgtm

#131 Increase documentation coverage
  certification/certification.go
  certification/engine/engine.go
  certification/formatters/formatters.go
  certification/formatters/util.go
  certification/internal/shell/base_on_ubi.go
  certification/internal/shell/has_license.go
  certification/internal/shell/has_minimal_vulns.go
  certification/internal/shell/has_prohibited_packages.go
  certification/internal/shell/has_required_labels.go
  certification/internal/shell/has_unique_tag.go
  certification/internal/shell/less_than_max_layers.go
  certification/internal/shell/runs_as_nonroot.go
  certification/internal/shell/scorecard_basic_check_spec.go
  certification/internal/shell/scorecard_olm_suite.go
  certification/internal/shell/validate_operator_bundle.go
  certification/runtime/runtime.go
  cmd/root.go
  docs/dev/IMPLEMENT_A_CHECK.md
  docs/dev/README.md
Labels: lgtm

#129 Fix a couple of linter issues
  certification/internal/shell/less_than_max_layers_test.go
  certification/internal/shell/validate_operator_bundle_test.go
Labels: lgtm

#126 Add a new command to run preflight in an unshare namespace
  certification/engine/engine.go
  certification/errors/errors.go
  certification/internal/shell/has_prohibited_packages.go
  certification/internal/shell/has_prohibited_packages_mounted.go
  certification/internal/shell/has_prohibited_packages_test.go
  certification/internal/shell/mounted_engine.go
  certification/internal/shell/podman.go
  certification/internal/shell/shell_suite_test.go
  certification/internal/utils/container/helper.go
  certification/runtime/runtime.go
  cli/podman.go
  cmd/check_run.go
  go.mod
  go.sum
Labels: lgtm

#124 Implements bundle check ensuring CSV related images are schema version 2
  certification/engine/engine.go
  certification/errors/errors.go
  certification/internal/shell/has_v2_related_image_schema_version.go
  certification/internal/shell/has_v2_related_image_schema_version_test.go
  go.mod
  go.sum
Labels: lgtm
