Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2022-02, with the labels that each got.

#382 removing calls to SetUsageTemplate, instead adding in a flag list-checks
  cmd/check.go
  cmd/check_container.go
  cmd/check_operator.go
Labels: lgtm, approved, ok-to-test

#386 Move BundleValidate to a standalone method and call from DBOLM
  certification/engine/engine.go
  certification/internal/bundle/bundle.go
  certification/internal/bundle/bundle_suite_test.go
  certification/internal/bundle/bundle_test.go
  certification/internal/policy/operator/default.go
  certification/internal/policy/operator/deployable_by_olm.go
  certification/internal/policy/operator/deployable_by_olm_test.go
  certification/internal/policy/operator/operator.go
  certification/internal/policy/operator/operator_pkg_name_uniqueness.go
  certification/internal/policy/operator/operator_test.go
  certification/internal/policy/operator/validate_operator_bundle.go
  certification/internal/policy/operator/validate_operator_bundle_test.go
Labels: lgtm, approved

#388 Introduce Pyxis Engine
  certification/errors/errors.go
  certification/internal/engine/pyxis.go
  cmd/check_container.go
  cmd/defaults.go
  cmd/utils.go
  docs/CONFIG.md
Labels: lgtm, approved

#383 build multi arch images for main and release
  .github/workflows/build-main.yml
  .github/workflows/build-ppc64le.yaml
  .github/workflows/build-release.yml
  .github/workflows/release-artifacts.yml
  Dockerfile
Labels: lgtm, approved, ok-to-test

#391 replace the invalid image plus with a hyphen
  .github/workflows/build-main.yml
Labels: lgtm, approved, ok-to-test

#396 Use qemu action instead of apt install
  .github/workflows/build-main.yml
  .github/workflows/build-release.yml
Labels: ok-to-test

#399 default pyxis host
  docs/CONFIG.md
Labels: lgtm, approved, ok-to-test

#393 Parameterize the IMAGE_REGISTRY in Actions
  .github/workflows/build-main.yml
  .github/workflows/build-release.yml
Labels: lgtm, approved

#408 Enable WaitContainer to timeout if the container does not reach the running state
  certification/internal/cli/podman.go
  certification/internal/engine/podman.go
  certification/internal/policy/container/defaults.go
  certification/internal/policy/container/runnable_container.go
Labels: lgtm, approved

#405 Add Unit tests for RunnableContainerCheck
  certification/internal/policy/container/container_suite_test.go
  certification/internal/policy/container/runnable_container_test.go
Labels: lgtm, approved

#412 Changes uses of make to be more idiomatic Go
  certification/engine/engine.go
  certification/formatters/util.go
  certification/internal/policy/container/has_prohibited_packages.go
  certification/internal/policy/operator/deployable_by_olm.go
  certification/runtime/assets.go
Labels: lgtm, approved

#406 Make GetProject an exported method of PyxisEngine
  certification/engine/engine.go
  certification/pyxis/pyxis.go
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
  certification/pyxis/types.go
  cmd/check_container.go
Labels: lgtm, approved

#413 After a certain point in the command, silence the usage output
  cmd/check_container.go
  cmd/check_operator.go
Labels: approved

#414 add a reusable multiarch manifest action
  .github/workflows/build-main.yml
  .github/workflows/build-multiarch.yml
  .github/workflows/build-release.yml
Labels: lgtm, approved, ok-to-test

#402 implementing submit flag and saving cert image info and rpm manifest information to disk
  certification/defaults.go
  certification/errors/errors.go
  certification/internal/engine/engine.go
  certification/pyxis/pyxis.go
  certification/pyxis/pyxis_suite_test.go
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
  certification/pyxis/types.go
  cmd/check_container.go
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#410 Implement RunAsSystemContainer Check
  certification/defaults.go
  certification/engine/engine.go
  certification/internal/cli/podman.go
  certification/internal/engine/podman.go
  certification/internal/policy/container/container_suite_test.go
  certification/internal/policy/container/run_system_container.go
  certification/internal/policy/container/run_system_container_test.go
Labels: lgtm, approved

#417 Move the defer statement to after error checks
  cmd/check_container.go
Labels: lgtm, approved

#418 refactoring to make project id and api token required flags
  cmd/check_container.go
  cmd/check_operator.go
Labels: lgtm, approved

#424 Fixing a bug in upload of binaries to the release
  .github/workflows/release-artifacts.yml
Labels: lgtm, needs-ok-to-test, approved

#421 Use the submit variable where possible
  cmd/check_container.go
Labels: lgtm, approved

#419 handling non-200 responses from all pyxis calls
  certification/errors/errors.go
  certification/pyxis/pyxis.go
  certification/pyxis/pyxis_suite_test.go
  certification/pyxis/submit.go
Labels: lgtm, approved

#423 Add image_id to the test results
  certification/pyxis/pyxis.go
  certification/pyxis/submit.go
  certification/pyxis/types.go
Labels: approved

#429 Add RunAsSystemContainer check to the scratch image policy
  certification/engine/engine.go
Labels: lgtm, approved

#428 Use a more strict 'go fmt'
  Makefile
  certification/artifacts/artifacts.go
  certification/engine/engine.go
  certification/errors/errors.go
  certification/formatters/formatters_test.go
  certification/internal/bundle/bundle.go
  certification/internal/bundle/bundle_test.go
  certification/internal/cli/openshift.go
  certification/internal/client/subscription.go
  certification/internal/engine/engine.go
  certification/internal/engine/openshift.go
  certification/internal/engine/podman.go
  certification/internal/policy/container/base_on_ubi_test.go
  certification/internal/policy/container/has_license_test.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/policy/container/run_system_container_test.go
  certification/internal/policy/container/runnable_container_test.go
  certification/internal/policy/operator/deployable_by_olm.go
  certification/internal/policy/operator/deployable_by_olm_test.go
  certification/internal/policy/operator/operator_suite_test.go
  certification/internal/policy/operator/validate_operator_bundle_test.go
  certification/pyxis/pyxis.go
  certification/pyxis/submit_test.go
  certification/pyxis/types.go
  certification/runtime/assets.go
  cmd/check_container.go
  cmd/check_operator.go
  cmd/support.go
  cmd/utils.go
  test/e2e/e2e_test.go
  version/version.go
Labels: lgtm, approved

#427 Simplify the handling of the API token
  certification/pyxis/pyxis.go
Labels: lgtm, approved

#431 Add a doc describing how to find uncompressed layer IDs
  docs/dev/LAYER_IDS.md
Labels: lgtm, approved

#430 Add layer information to the results
  certification/internal/engine/engine.go
  certification/pyxis/pyxis.go
  certification/pyxis/types.go
Labels: lgtm, approved

#432 displaying response information to the user after results have been submitted
  cmd/check_container.go
  cmd/defaults.go
Labels: approved

#437 update gh release action so preflight can support alpha, beta and rc releases
  .github/workflows/build-release.yml
Labels: lgtm, approved

#439 Limit the usage of log.Info
  certification/internal/engine/engine.go
  certification/internal/engine/podman.go
  certification/internal/policy/container/has_license.go
  certification/internal/policy/operator/deployable_by_olm.go
  cmd/utils.go
Labels: lgtm, approved

#440 making fixes to the data that we marshal and send to pxyis
  certification/formatters/util.go
  certification/pyxis/pyxis.go
  certification/pyxis/types.go
  cmd/check_container.go
Labels: lgtm, approved

#444 Disable runnable checks for now
  certification/engine/engine.go
Labels: lgtm, approved
