Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2022-01, with the labels that each got.

#359 Added label for building image for ppc64le architecture
  Dockerfile
Labels: lgtm

#362 updating dependencies and go version
  .github/workflows/go.yml
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#364 Fixing Grammar Mistakes in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, approved, ok-to-test

#363 Add e2e integration and docs
  docs/dev/TESTING.md
Labels: lgtm, approved

#360 Dynamic Help() response
  certification/internal/policy/operator/scorecard_basic_check_spec.go
  certification/internal/policy/operator/scorecard_olm_suite.go
Labels: lgtm, approved

#356 updating FATA string comparison to convert the error we get back from scorecard test
  certification/internal/engine/operatorsdk.go
Labels: lgtm, approved

#368 adding in optional SCORECARD_WAIT_TIME env variable to pass to scorecard
  certification/internal/policy/operator/scorecard_check.go
  cmd/defaults.go
  cmd/utils.go
  docs/CONFIG.md
Labels: lgtm, approved, ok-to-test

#385 adding in ARG ARCH in the main container build stage
  Dockerfile
Labels: lgtm, approved, ok-to-test
