Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2022-04, with the labels that each got.

#538 Fix nonroot home directory permissions
  Dockerfile
Labels: lgtm, approved

#545 Reverting user changes
  Dockerfile
Labels: lgtm, approved, ok-to-test

#548 fix typo in certification-project-id flag
  cmd/check_container.go
Labels: lgtm, approved

#550 Build make target only looks for the preflight binary on build
  Makefile
Labels: lgtm, approved

#540 no longer throw exceptions back for RPM manifests
  certification/errors/errors.go
  certification/internal/engine/engine.go
  certification/internal/rpm/rpm.go
Labels: lgtm, approved, ok-to-test

#553 Move OsContentType to CertProjectContainer
  certification/pyxis/types.go
  cmd/check_container.go
Labels: lgtm, approved

#555 Document workflow for submitting container check results to red hat
  certification/errors/errors.go
  certification/internal/engine/engine.go
  certification/pyxis/pyxis.go
  certification/pyxis/submit.go
  cmd/check_container.go
  cmd/utils.go
Labels: lgtm, approved

#554 adding clarity to logs when GetPackageList is called
  certification/errors/errors.go
  certification/internal/engine/engine.go
  certification/internal/policy/container/has_modified_files.go
  certification/internal/policy/container/has_prohibited_packages.go
Labels: lgtm, approved

#559 Clarify the graphql layer checking logic
  certification/internal/policy/container/base_on_ubi.go
  certification/internal/policy/container/base_on_ubi_test.go
  certification/pyxis/layers.go
  certification/pyxis/layers_test.go
Labels: lgtm, approved

#560 Remove redundant alpha tag from the version displayed in results.json/test_library
  .github/workflows/build-main.yml
Labels: lgtm, approved, ok-to-test

#558 Make the pulling of the project to check for scratch optional
  certification/errors/errors.go
  cmd/check_container.go
  docs/RECIPES.md
Labels: approved

#561 HasNoProhibitedPackages check has an incorrect name. Fix it.
  certification/internal/policy/container/has_prohibited_packages.go
Labels: lgtm, approved

#556 Convert submission logic to use a builder struct
  certification/pyxis/builder.go
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
  certification/pyxis/types.go
  cmd/check_container.go
  cmd/utils.go
Labels: lgtm, approved

#565 Add environment variables to --help output
  cmd/check_container.go
Labels: lgtm, approved

#567 Simplify the install of go tools
  Makefile
Labels: lgtm, approved

#566 Prefer the usage of pyxis env instead of pyxis host
  certification/defaults.go
  cmd/check_container.go
Labels: lgtm, approved

#564 Refactor and simplify some of the file reading
  certification/pyxis/builder.go
  certification/pyxis/builder_test.go
  cmd/check_container.go
Labels: lgtm, approved

#569 adding in RootExceptionContainerPolicy check list
  certification/engine/engine.go
  certification/pyxis/types.go
  cmd/check_container.go
Labels: lgtm, approved

#572 removing pyxis host and api key from viper in init
  cmd/check_container.go
  cmd/utils.go
Labels: lgtm, approved

#574 updating recipes file to include a way to run `check container`
  docs/RECIPES.md
Labels: lgtm, approved

#580 Make the Connect URLs match the environment given
  cmd/utils.go
  cmd/utils_test.go
Labels: lgtm, approved

#581 updating check container check url in all checks
  certification/internal/policy/container/base_on_ubi.go
  certification/internal/policy/container/defaults.go
  certification/internal/policy/container/has_license.go
  certification/internal/policy/container/has_modified_files.go
  certification/internal/policy/container/has_prohibited_packages.go
  certification/internal/policy/container/has_required_labels.go
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/max_layers.go
  certification/internal/policy/container/run_system_container.go
  certification/internal/policy/container/runnable_container.go
  certification/internal/policy/container/runs_as_nonroot.go
Labels: lgtm, approved

#587 updating vagrant file to change the port
  Vagrantfile
Labels: lgtm, approved

#582 Copy the binaries for release out of the containers
  .github/workflows/build-release.yml
  .github/workflows/release-artifacts.yml
  Makefile
Labels: lgtm, approved

#590 Backports from main
  .github/workflows/build-release.yml
  .github/workflows/release-artifacts.yml
  Makefile
  certification/internal/policy/container/base_on_ubi.go
  certification/internal/policy/container/defaults.go
  certification/internal/policy/container/has_license.go
  certification/internal/policy/container/has_modified_files.go
  certification/internal/policy/container/has_prohibited_packages.go
  certification/internal/policy/container/has_required_labels.go
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/max_layers.go
  certification/internal/policy/container/run_system_container.go
  certification/internal/policy/container/runnable_container.go
  certification/internal/policy/container/runs_as_nonroot.go
  docs/CONFIG.md
  docs/RECIPES.md
Labels: lgtm, approved

#591 Copy release images to redhat-isv on quay
  .github/workflows/build-release.yml
  .github/workflows/copy-to-rhisv.yml
Labels: lgtm, approved
