Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2022-07, with the labels that each got.

#728 Add tests confirming check metadata is never empty
  certification/internal/policy/container/base_on_ubi_test.go
  certification/internal/policy/container/has_license_test.go
  certification/internal/policy/container/has_modifed_files_test.go
  certification/internal/policy/container/has_prohibited_packages_test.go
  certification/internal/policy/container/has_required_labels_test.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/policy/container/max_layers_test.go
  certification/internal/policy/container/runs_as_nonroot_test.go
  certification/internal/policy/operator/deployable_by_olm_test.go
  certification/internal/policy/operator/scorecard_basic_check_spec_test.go
  certification/internal/policy/operator/scorecard_olm_suite_test.go
  certification/internal/policy/operator/validate_operator_bundle_test.go
Labels: approved

#729 Extract the metadata tests to a separate function
  certification/internal/policy/container/base_on_ubi_test.go
  certification/internal/policy/container/container_suite_test.go
  certification/internal/policy/container/has_license_test.go
  certification/internal/policy/container/has_modifed_files_test.go
  certification/internal/policy/container/has_prohibited_packages_test.go
  certification/internal/policy/container/has_required_labels_test.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/policy/container/max_layers_test.go
  certification/internal/policy/container/runs_as_nonroot_test.go
  certification/internal/policy/operator/deployable_by_olm_test.go
  certification/internal/policy/operator/operator_suite_test.go
  certification/internal/policy/operator/scorecard_basic_check_spec_test.go
  certification/internal/policy/operator/scorecard_olm_suite_test.go
  certification/internal/policy/operator/validate_operator_bundle_test.go
Labels: lgtm, approved

#733 Add fallback paths to credential resolution when using docker.io as your registry
  certification/internal/authn/keychain.go
  certification/internal/authn/keychain_test.go
Labels: lgtm, approved

#702 Fallback to cli tag in container HasUniqueTag test
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/has_unique_tag_test.go
Labels: approved, ok-to-test

#735 Wait for layer file processing to complete before proceeding
  certification/internal/policy/container/has_modified_files.go
Labels: lgtm, approved

#742 inform the user of tag and digest binding semantics for container certification
  certification/internal/engine/engine.go
  certification/internal/engine/engine_test.go
Labels: lgtm, approved

#743 Add a check for certified images in the CSV
  certification/engine/engine.go
  certification/internal/bundle/bundle.go
  certification/internal/bundle/bundle_test.go
  certification/internal/policy/operator/certified_images.go
  certification/internal/policy/operator/certified_images_test.go
  certification/pyxis/pyxis.go
  go.mod
  go.sum
Labels: lgtm, approved

#746 Re-adds basedOnUBI check to root policy exception
  certification/engine/engine.go
Labels: lgtm, approved
