Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2022-03, with the labels that each got.

#450 removing --submit check when writing image config and rpm manifest to disk
  certification/internal/engine/engine.go
Labels: lgtm, approved

#449 Add PGP key id to the RPM manifest
  certification/internal/engine/engine.go
  go.mod
  go.sum
Labels: lgtm, approved

#451 Add a flag to specify an image as a scratch image
  certification/engine/engine.go
  certification/internal/engine/engine.go
  certification/runtime/runtime.go
  cmd/check_container.go
  cmd/check_operator.go
Labels: lgtm, approved

#456 Check for sqlite RPM database
  certification/internal/engine/engine.go
  certification/internal/policy/container/has_prohibited_packages.go
Labels: lgtm, approved

#448 adding in a call to pyxis getImage so preflight can run multiple times
  certification/errors/errors.go
  certification/pyxis/pyxis.go
  certification/pyxis/pyxis_suite_test.go
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
Labels: lgtm, approved

#458 match catalog url and connect url
  cmd/check_container.go
Labels: lgtm, approved

#463 Fix typo - redundant space in API parameter
  certification/pyxis/types.go
Labels: lgtm, approved

#459 adding in repositories information for create image pyxis call
  certification/errors/errors.go
  certification/internal/engine/engine.go
Labels: lgtm, approved

#466 Pass docker config to the results upload
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
  cmd/check.go
  cmd/check_container.go
  cmd/utils.go
  docs/CONFIG.md
Labels: lgtm, approved

#462 making certImage.certified match testResults.passed
  certification/pyxis/types.go
  cmd/check_container.go
Labels: lgtm, approved

#474 updating readme with the latest acceptable commands
  README.md
Labels: lgtm, approved

#471 Add some useful fields to ImageReference
  certification/certification.go
  certification/errors/errors.go
  certification/internal/engine/engine.go
  certification/types.go
Labels: lgtm, approved

#468 using crane's name package to determine the format of the registry
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/has_unique_tag_test.go
Labels: lgtm, approved

#469 adding in scan results url to output and changing to the mongo db _id
  cmd/check_container.go
Labels: lgtm, approved

#476 added in layers array into ParsedData struct since this is required
  certification/internal/engine/engine.go
  certification/pyxis/types.go
Labels: lgtm, approved

#477 Refactor url building for DRY
  cmd/check_container.go
  cmd/utils.go
  cmd/utils_test.go
Labels: lgtm, approved

#479 Reorder the steps in the go action
  .github/workflows/go.yml
Labels: lgtm, approved

#473 adding in createArtifacts method so we can send pyxis the preflight.log
  certification/pyxis/pyxis.go
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
  certification/pyxis/types.go
  cmd/check_container.go
Labels: lgtm, approved

#478 Upgrade ginkgo test suite to v2
  certification/engine/engine_suite_test.go
  certification/engine/engine_test.go
  certification/formatters/formatters_suite_test.go
  certification/formatters/formatters_test.go
  certification/internal/bundle/bundle_test.go
  certification/internal/policy/container/base_on_ubi_test.go
  certification/internal/policy/container/container_suite_test.go
  certification/internal/policy/container/has_license_test.go
  certification/internal/policy/container/has_prohibited_packages_test.go
  certification/internal/policy/container/has_required_labels_test.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/policy/container/max_layers_test.go
  certification/internal/policy/container/run_system_container_test.go
  certification/internal/policy/container/runnable_container_test.go
  certification/internal/policy/container/runs_as_nonroot_test.go
  certification/internal/policy/operator/deployable_by_olm_test.go
  certification/internal/policy/operator/operator_pkg_name_uniqueness_test.go
  certification/internal/policy/operator/operator_suite_test.go
  certification/internal/policy/operator/scorecard_basic_check_spec_test.go
  certification/internal/policy/operator/scorecard_olm_suite_test.go
  certification/internal/policy/operator/validate_operator_bundle_test.go
  certification/pyxis/pyxis_suite_test.go
  certification/pyxis/submit_test.go
  cmd/suite_test.go
  cmd/utils_test.go
  go.mod
  go.sum
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: lgtm, approved

#457 remove `options` from `crane.ListTags`
  certification/internal/engine/crane.go
Labels: lgtm, approved

#483 Check for modified base layer files
  certification/engine/engine.go
  certification/errors/errors.go
  certification/internal/engine/engine.go
  certification/internal/policy/container/has_modifed_files_test.go
  certification/internal/policy/container/has_modified_files.go
  certification/internal/policy/container/has_prohibited_packages.go
  certification/internal/rpm/rpm.go
Labels: lgtm, approved

#487 Revert "Update go-rpmdb to the latest downstream"
  go.mod
  go.sum
Labels: lgtm, approved

#489 Fail multi-arch-build on any failure
  Makefile
Labels: approved

#491 Ignore multi-arch binaries from git
  .gitignore
Labels: lgtm, approved

#492 Write project id back to viper if modified
  cmd/check_container.go
Labels: lgtm, approved

#493 updating gitignore to include check container
  .gitignore
Labels: lgtm, approved

#496 updated comment for HasModifiedFilesCheck
  certification/internal/policy/container/has_modified_files.go
Labels: lgtm, approved, ok-to-test

#482 check image under test for a certified uncompressed top layer id
  certification/engine/engine.go
  certification/internal/policy/container/base_on_ubi.go
  certification/internal/policy/container/base_on_ubi_test.go
  certification/pyxis/layers.go
Labels: lgtm, approved

#501 using registry/repository/tag information from imageRef struct
  certification/internal/engine/engine.go
Labels: lgtm, approved

#498 Simplify Pyxis Submit call
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
  certification/pyxis/types.go
  cmd/check_container.go
Labels: lgtm, approved

#499 Introduce context param throughout the codebase
  certification/certification.go
  certification/engine/engine.go
  certification/formatters/formatters.go
  certification/formatters/formatters_test.go
  certification/formatters/generic.go
  certification/formatters/generic_test.go
  certification/formatters/junitxml.go
  certification/generic_check.go
  certification/internal/bundle/bundle.go
  certification/internal/bundle/bundle_test.go
  certification/internal/engine/engine.go
  certification/internal/policy/container/base_on_ubi.go
  certification/internal/policy/container/base_on_ubi_test.go
  certification/internal/policy/container/has_license.go
  certification/internal/policy/container/has_license_test.go
  certification/internal/policy/container/has_modified_files.go
  certification/internal/policy/container/has_prohibited_packages.go
  certification/internal/policy/container/has_prohibited_packages_test.go
  certification/internal/policy/container/has_required_labels.go
  certification/internal/policy/container/has_required_labels_test.go
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/policy/container/max_layers.go
  certification/internal/policy/container/max_layers_test.go
  certification/internal/policy/container/run_system_container.go
  certification/internal/policy/container/run_system_container_test.go
  certification/internal/policy/container/runnable_container.go
  certification/internal/policy/container/runnable_container_test.go
  certification/internal/policy/container/runs_as_nonroot.go
  certification/internal/policy/container/runs_as_nonroot_test.go
  certification/internal/policy/operator/deployable_by_olm.go
  certification/internal/policy/operator/deployable_by_olm_test.go
  certification/internal/policy/operator/operator_pkg_name_uniqueness.go
  certification/internal/policy/operator/operator_pkg_name_uniqueness_test.go
  certification/internal/policy/operator/scorecard_basic_check_spec.go
  certification/internal/policy/operator/scorecard_basic_check_spec_test.go
  certification/internal/policy/operator/scorecard_check.go
  certification/internal/policy/operator/scorecard_olm_suite.go
  certification/internal/policy/operator/scorecard_olm_suite_test.go
  certification/internal/policy/operator/validate_operator_bundle.go
  certification/internal/policy/operator/validate_operator_bundle_test.go
  certification/internal/rpm/rpm.go
  cmd/check.go
  cmd/check_container.go
  cmd/check_operator.go
  test/e2e/e2e_test.go
Labels: lgtm, approved

#504 updating support cmd to only add pull_request_url for bundle
  cmd/support.go
Labels: lgtm, approved

#507 fix url for call to search for layers
  certification/internal/policy/container/base_on_ubi.go
  certification/pyxis/layers.go
Labels: lgtm, approved

#512 Add a license
  Dockerfile
Labels: lgtm, approved, ok-to-test

#511 unsupported image error in case rpm path isn't found
  certification/errors/errors.go
  certification/internal/rpm/rpm.go
Labels: lgtm, approved, ok-to-test

#513 Set a non-root user
  Dockerfile
Labels: lgtm, approved, ok-to-test

#509 Make pyxis tests more robust
  certification/pyxis/pyxis_suite_test.go
  certification/pyxis/submit_test.go
Labels: approved

#515 Fixing a bug introduced with non-root
  Dockerfile
Labels: lgtm, approved, ok-to-test

#514 log pyxis layer check request
  certification/pyxis/layers.go
Labels: lgtm, approved

#518 Force use of prod pyxis for Based On UBI check
  certification/engine/engine.go
  certification/internal/policy/container/base_on_ubi.go
  certification/internal/policy/container/base_on_ubi_test.go
  certification/pyxis/layers.go
  certification/pyxis/pyxis.go
  certification/pyxis/submit_test.go
  cmd/check_container.go
Labels: lgtm, approved

#520 Use the default pyxis host for BasedOnUBI
  certification/defaults.go
  certification/engine/engine.go
  cmd/check_container.go
  cmd/defaults.go
  cmd/utils.go
Labels: lgtm, approved

#525 Detect if layer 0 is non-zero length and shift to layer 1
  certification/internal/policy/container/has_modified_files.go
  certification/internal/rpm/rpm.go
  cmd/check_container.go
Labels: lgtm, approved

#531 Update go-rpmdb to latest midstream main
  go.mod
  go.sum
Labels: lgtm, approved

#532 Fix source rpm name parsing
  certification/internal/engine/engine.go
  certification/internal/engine/engine_test.go
  certification/internal/engine/internal_engine_suite_test.go
Labels: lgtm, approved

#534 Utilize built-in cache of crane library
  certification/errors/errors.go
  certification/internal/engine/engine.go
Labels: lgtm, approved

#537 updating RunAsNonRoot logs to be info level and provide more details
  certification/internal/policy/container/runs_as_nonroot.go
Labels: lgtm, approved
