Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2022-05, with the labels that each got.

#588 Use --docker-config for crane if specified
  README.md
  certification/internal/authn/keychain.go
  certification/internal/authn/keychain_test.go
  certification/internal/engine/crane.go
  certification/internal/engine/engine.go
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/service/service.go
  certification/pyxis/types.go
  certification/runtime/assets.go
  cmd/check.go
  cmd/check_container.go
  cmd/runtime-assets.go
  docs/RECIPES.md
  go.mod
Labels: lgtm, approved

#592 Fix a data race exposed by race checker
  Makefile
  certification/internal/policy/operator/deployable_by_olm.go
Labels: lgtm, approved

#595 Run tests on release branches
  .github/workflows/go.yml
Labels: approved

#594 Bug fixes from main
  README.md
  certification/internal/authn/keychain.go
  certification/internal/authn/keychain_test.go
  certification/internal/engine/crane.go
  certification/internal/engine/engine.go
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/service/service.go
  certification/pyxis/types.go
  certification/runtime/assets.go
  cmd/check.go
  cmd/check_container.go
  cmd/check_test.go
  cmd/runtime-assets.go
  docs/RECIPES.md
  go.mod
Labels: lgtm, approved

#601 [Backport] Run tests on release branches
  .github/workflows/go.yml
Labels: lgtm, approved

#599 Remove extra return and add test coverage to pyxis input builder
  certification/pyxis/builder.go
  certification/pyxis/builder_test.go
Labels: lgtm, approved

#602 add preflight-specific labels to the resulting container image
  Dockerfile
  Makefile
Labels: lgtm, approved

#604 updating a few of the help texts
  cmd/check.go
  cmd/check_container.go
Labels: lgtm, approved

#605 Increase Pyxis test coverage
  certification/pyxis/pyxis.go
  certification/pyxis/pyxis_suite_test.go
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
Labels: lgtm, approved

#623 Increase coverage of the internal/bundle package
  certification/errors/errors.go
  certification/internal/bundle/bundle.go
  certification/internal/bundle/bundle_suite_test.go
  certification/internal/bundle/bundle_test.go
  certification/internal/policy/operator/deployable_by_olm.go
  certification/internal/policy/operator/operator_pkg_name_uniqueness.go
Labels: lgtm, approved

#624 Increase test coverage of the version package
  Makefile
  version/version_suite_test.go
  version/version_test.go
Labels: lgtm, approved

#625 Increase test coverage of the certification/artifacts
  certification/artifacts/artifacts_test.go
  certification/artifacts/suite_test.go
Labels: lgtm, approved

#630 Refactor hasUniqueTagCheck to get rid of CraneEngine
  certification/engine/engine.go
  certification/internal/engine/crane.go
  certification/internal/policy/container/has_unique_tag.go
  certification/internal/policy/container/has_unique_tag_test.go
  certification/internal/service/service.go
  go.sum
Labels: lgtm, approved

#629 Fix the coverage of the certification package
  certification/certification_suite_test.go
  certification/generic_check_test.go
Labels: lgtm, approved

#634 always update the cert project in pyxis
  certification/pyxis/submit.go
Labels: lgtm, approved

#637 ioutil calls deprecated
  certification/internal/authn/keychain_test.go
Labels: lgtm, approved, ok-to-test

#638 Fix typos
  certification/internal/policy/operator/deployable_by_olm.go
  certification/internal/policy/operator/operator_pkg_name_uniqueness.go
Labels: lgtm, approved, ok-to-test

#636 Refactor Openshift engine to increase testability
  certification/engine/engine.go
  certification/internal/bundle/bundle.go
  certification/internal/bundle/bundle_test.go
  certification/internal/client/catalogsource.go
  certification/internal/client/client.go
  certification/internal/client/csv.go
  certification/internal/client/operatorgroup.go
  certification/internal/client/subscription.go
  certification/internal/engine/openshift.go
  certification/internal/engine/openshift_test.go
  certification/internal/engine/openshift_version.go
  certification/internal/policy/operator/deployable_by_olm.go
  certification/internal/policy/operator/deployable_by_olm_test.go
  certification/internal/policy/operator/operator_suite_test.go
  certification/internal/policy/operator/validate_operator_bundle.go
  go.mod
  go.sum
Labels: lgtm, approved

#651 normalize docker registries to `docker.io` for the cert image
  certification/pyxis/pyxis_suite_test.go
  certification/pyxis/submit.go
  certification/pyxis/submit_test.go
Labels: lgtm, approved

#667 Report coverage in a PR comment
  .github/workflows/go.yml
  README.md
Labels: lgtm, approved

#654 Normalize error handling
  certification/artifacts/artifacts.go
  certification/engine/engine.go
  certification/engine/errors.go
  certification/formatters/errors.go
  certification/formatters/formatters.go
  certification/formatters/formatters_test.go
  certification/formatters/generic.go
  certification/formatters/junitxml.go
Labels: lgtm, approved

#675 Encapsulate authn errors
  certification/internal/authn/keychain.go
Labels: lgtm, approved

#674 Do not expose all errors from rpm package
  certification/internal/rpm/rpm.go
Labels: lgtm, approved

#673 Fix errors and return values
  certification/internal/openshift/errors.go
  certification/internal/openshift/openshift.go
  certification/internal/openshift/openshift_version.go
  certification/internal/policy/operator/deployable_by_olm.go
Labels: lgtm, approved
