Repository redhat-openshift-ecosystem/openshift-preflight, pull requests merged in 2023-10, with the labels that each got.

#1070 feat: add --config flag to allow different config files to be passed
  cmd/preflight/cmd/root.go
Labels: lgtm, approved, ok-to-test

#1074 Update doc url
  README.md
  internal/policy/container/defaults.go
  internal/policy/operator/certified_images.go
  internal/policy/operator/related_images.go
  internal/policy/operator/restricted_network_aware.go
Labels: lgtm, approved, ok-to-test

#1081 updating to operator-sdk v1.32.0
  Dockerfile
  README.md
  Vagrantfile
  docs/dev/README.md
  internal/policy/operator/testdata/disconnected_bundle/manifests/simple-disconnected-operator.clusterserviceversion.yaml
  internal/policy/operator/testdata/disconnected_bundle/metadata/annotations.yaml
  internal/runtime/assets.go
Labels: lgtm, approved

#1085 Do not process attestation manifests
  cmd/preflight/cmd/check_container.go
  cmd/preflight/cmd/check_container_test.go
Labels: lgtm, approved

#1090 updating ocp to k8s map for latest release
  internal/bundle/bundle.go
  internal/bundle/bundle_test.go
Labels: approved

#1079 updating gomega to version 1.28.0
  go.mod
  go.sum
Labels: approved

#1082 updating go to 1.21
  Dockerfile
  Vagrantfile
  go.mod
  go.sum
Labels: lgtm, approved
